server:
  port: 8080


#  配置spring默认参数
spring:
  datasource:
    name: mytest
    url: jdbc:mysql://127.0.0.1:3306/springboot?allowMultiQueries=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true
    username: root
    password: 123456
#   type 选定要用的数据源
    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: com.mysql.jdbc.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
#   实际上 只配置这些是不能绑定在DataSource里面的 , 还需要进行绑定 , 配置自己的数据源文件
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    poolPreparedStatements: true


  redis:
    host: 127.0.0.1
    port: 6379
    password: redis-1.0
    timeout: 15000ms
    lettuce:
      pool:
        min-idle: 0
        max-idle: 18
        max-active: 18


  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    timezone: GMT+8

  thymeleaf:
    prefix: classpath:/resources/
    suffix: .html
    cache: false


#mybatis
mybatis-plus:
  mapperLocations: classpath*:/mybatis/mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.qsq.template.db.base.bean
  global-config:
    # 数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
#      id-type: id_worker
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
#      field-strategy: not_empty
      #驼峰下划线转换
      column-underline: true
      #逻辑删除配置
      logic-delete-value: 1
      logic-not-delete-value: 0
      db-type: mysql
#      table-prefix: ssm_
    #刷新mapper 调试神器
    refresh: true

  # mybatis原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

logging:
  config: classpath:config/log4j2-dev.xml

#  生产 pro 系统环境
environment: dev